version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 10
    commands:
      - echo Installing source NPM dependencies...
      - npm install
      - npm install -g @angular/cli
  build:
    commands:
      - echo Build started 
      - ng build
artifacts:
  files:
    - '**/*'
  base-directory: 'dist/ng-ci-cd-aws-demo/*'
  discard-paths: no