#0.1 runs each build command in a separate instance --- 0.2 runs all build command in a same instance (recommanded)
version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 10
    commands:
      - echo Installing source NPM dependencies...
      - npm install -g @angular/cli
      - npm install
  build:
    commands:
      - echo Build started 
      - ng build
artifacts:
  files:
    - '**/*'
  base-directory: 'dist*'
  discard-paths: yes